export const drones = [
    {
        id: 1,
        name: 'Crop Sprayer Pro',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-1.jpg',
        description: 'High-capacity drone designed for efficient and precise crop spraying, covering large areas quickly.',
    },
    {
        id: 2,
        name: 'SoilScan 360',
        drone_type: 'Fixed-wing',
        image: '/images/drones/drone-2.jpg',
        description: 'Long-range drone equipped with advanced sensors for comprehensive soil analysis and mapping.',
    },
    {
        id: 3,
        name: 'PlantHealth Sentinel',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-3.jpg',
        description: 'Specialized drone with multispectral imaging for early detection of crop diseases and nutrient deficiencies.',
    },
    {
        id: 4,
        name: 'Precision Seeder',
        drone_type: 'VTOL',
        image: '/images/drones/drone-1.jpg',
        description: 'Vertical takeoff and landing drone capable of precise seed planting in various terrains.',
    },
    {
        id: 5,
        name: 'IrriDrone X1',
        drone_type: 'Single-rotor',
        image: '/images/drones/drone-2.jpg',
        description: 'Powerful single-rotor drone for targeted irrigation, equipped with water tanks and precision nozzles.',
    },
    {
        id: 6,
        name: 'Livestock Monitor',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-3.jpg',
        description: 'Quiet, long-endurance drone for livestock monitoring and health assessment using thermal imaging.',
    },
    {
        id: 7,
        name: 'Harvest Scout',
        drone_type: 'Fixed-wing',
        image: '/images/drones/drone-1.jpg',
        description: 'High-speed fixed-wing drone for rapid crop yield estimation and harvest planning.',
    },
    {
        id: 8,
        name: 'FrostGuard Copter',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-2.jpg',
        description: 'Specialized drone for frost protection, circulating warm air over crops during cold nights.',
    },
    {
        id: 9,
        name: 'Pollinator Pro',
        drone_type: 'Nano',
        image: '/images/drones/drone-3.jpg',
        description: 'Tiny drone designed to assist in crop pollination, ideal for greenhouse and orchard use.',
    },
    {
        id: 10,
        name: 'Weed Terminator',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-1.jpg',
        description: 'Precision weeding drone using AI to identify and remove weeds with minimal chemical use.',
    },
    {
        id: 11,
        name: 'AquaFarm Surveyor',
        drone_type: 'Waterproof',
        image: '/images/drones/drone-2.jpg',
        description: 'Amphibious drone for surveying and monitoring aquaculture farms and water quality.',
    },
    {
        id: 12,
        name: 'NightWatch Agri-Guard',
        drone_type: 'VTOL',
        image: '/images/drones/drone-3.jpg',
        description: 'Autonomous security drone with night vision for 24/7 farm surveillance and wildlife detection.',
    },
    {
        id: 13,
        name: 'CompostCopter',
        drone_type: 'Heavy-lift',
        image: '/images/drones/drone-1.jpg',
        description: 'Large-capacity drone for efficient distribution of compost and organic fertilizers.',
    },
    {
        id: 14,
        name: 'Greenhouse Inspector',
        drone_type: 'Indoor',
        image: '/images/drones/drone-2.jpg',
        description: 'Compact indoor drone for monitoring climate conditions and plant health in greenhouses.',
    },
    {
        id: 15,
        name: 'Orchard Pruner',
        drone_type: 'Multi-rotor',
        image: '/images/drones/drone-3.jpg',
        description: 'Specialized drone equipped with pruning tools for maintaining fruit trees and vineyards.',
    },
    {
        id: 16,
        name: 'CropDuster 2000',
        drone_type: 'Fixed-wing',
        image: '/images/drones/drone-1.jpg',
        description: 'High-speed, large-capacity drone for efficient pesticide and fertilizer application over vast areas.',
    },
    {
        id: 17,
        name: 'SoilSampler X',
        drone_type: 'VTOL',
        image: '/images/drones/drone-2.jpg',
        description: 'Autonomous drone capable of collecting and analyzing soil samples from multiple field locations.',
    },
    {
        id: 18,
        name: 'HarvestHauler Pro',
        drone_type: 'Heavy-lift',
        image: '/images/drones/drone-3.jpg',
        description: 'Powerful drone designed for transporting harvested crops from field to collection points.',
    }
]