export const experts = [
    {
        id: 1,
        name: 'Milasan Adrian',
        phone: '+40749105311',
        email: 'milasan_adrian@yahoo.com',
        designation: 'Specialist in agricultura',
        image: '/images/experts/adrian-mialsan.jpg',
        available: true,
        cost: 10,
        cost_unit: 'Hectare',
        address: 'Transylvania',
        bio: 'Expert în AgriBusiness cu focus pe analiza culturilor și pesticide. Oferă servicii de consultanță pentru fermierii din Transilvania, combinând cunoștințe agronomice cu perspectiva de afaceri.',
        expertise: ['Analiza culturilor', 'Evaluare pesticide', 'Promovare agricolă']
    },
    {
        id: 2,
        name: 'Rafael Marian',
        phone: '+40770515749',
        email: 'rafaelingineragronom@yahoo.com',
        designation: 'Dr. ING.',
        image: '/images/experts/rafael-marian.jpg',
        available: true,
        cost: 10,
        cost_unit: 'Hectare',
        address: 'Cluj-Napoca',
        bio: 'Doctor inginer specializat în tehnologii moderne pentru agricultura convențională și ecologică. Oferă consultanță avansată pentru optimizarea practicilor agricole în regiunea Cluj-Napoca.',
        expertise: ['Agricultură convențională', 'Agricultură ecologică', 'Consultanță tehnică']
    },
    {
        id: 3,
        name: 'Șerban Mădălina',
        phone: '+40749339987',
        email: 'madalina.serban@droneagricole.ro',
        designation: 'Inginer agronom',
        image: '/images/experts/expert-placeholder.jpg',
        available: true,
        cost: 10,
        cost_unit: 'Hectare',
        address: 'Brașov',
        bio: 'Inginer agronom cu 8 ani de experiență în agricultură. Doctorand în fitopatologie, specializat în utilizarea dronelor pentru tratamente. Oferă consultanță pentru Drone Agricole RIAGRO.',
        expertise: ['Consultanță agronomică', 'Utilizare drone agricole', 'Fitopatologie']
    },
    {
        id: 4,
        name: 'Vali Ileasă',
        phone: '+40741212819',
        email: 'ileasa.ionel@yahoo.com',
        designation: 'Protecția plantelor',
        image: '/images/experts/expert-placeholder.jpg',
        available: true,
        cost: 10,
        cost_unit: 'Hectare',
        address: 'Bistrița Năsăud',
        bio: 'Expert în protecția plantelor cu masterat în domeniu. Peste 10 ani de experiență, oferind consultanță de specialitate în fermele din zona centrală a României.',
        expertise: ['Protecția plantelor', 'Consultanță agricolă', 'Managementul fermelor']
    },
    {
        id: 5,
        name: 'Vlad Cristian',
        phone: '+40727811507',
        email: 'evoecocrop@gmail.com',
        designation: 'Specialist Nutritia Plantelor',
        image: '/images/experts/expert-placeholder.jpg',
        available: true,
        cost: 10,
        cost_unit: 'Hectare',
        address: 'Sudul Romaniei',
        bio: 'Specialist în nutriția plantelor cu expertiză în tehnologii moderne de nutriție. Oferă consultanță pentru optimizarea producției agricole în sudul României.',
        expertise: ['Nutriția plantelor', 'Protecția culturilor', 'Tehnologii agricole']
    },

]